import React, { Component } from 'react'

import { Breadcrumb, BreadcrumbItem } from "../Breadcrumbs/Breadcrumbs";

import { useTranslation } from 'react-i18next';

const Common =()=> {
    const { t, i18n } = useTranslation(['']);
    const lang=i18n.language;
    let title=lang==="en"?"General information about the engine":lang==="ru"?"Общие сведения о двигателе":"Mühərrik haqqinda ümumi məlumatlar";
    let adres=lang==="en"?"/info/characteristic":lang==="ru"?"/info/xarateristiki":"/info/xarakteristika";
    let info2=lang==="en"?"General characteristics of TV3-117VM engine":lang==="ru"?"Общие характеристики двигателя ТВ3-117ВМ":"ТВ3-117ВМ müherrikin ümumi xarakteristikası";
    let info1=lang==="en"?"TB3-117BM Engine Subtopics":lang==="ru"?"Подтемы двигателя TB3-117M":"TB3-117BM mühərrikinə aid altmövzular";
    let content1=lang==="en"?"The power plant of the Mi-24 combat helicopter consists of two TVZ-117V turboshaft engines, as well as systems and devices that ensure the operation of the engines. The use of two engines in a helicopter power plant increases flight safety, since when one of them is turned off, the second ensures the continuation of the flight or the execution of a safe landing. The right and left engines of the power plant are interchangeable, provided that the exhaust pipe is turned.":lang==="ru"?"Силовая установка боевого вертолета Ми-24 состоит из двух турбовальных двигателей ТВЗ-117В, а также систем и устройств, обеспечивающих работу двигателей. Использование в вертолетной силовой установке двух двигателей повышает безопасность полета, так как при выключении одного из них второй обеспечивает продолжение полета или выполнение безопасной посадки. Правый и левый двигатели силовой установки взаимозаменяемы при условии разворота выхлопного патрубка.":"Mi-24 döyüş vertolyotunun güc qurğusu iki TVZ-117V turboval mühərrikdən, həmçinin mühərriklərin işini təmin edən sistem və qurğulardan ibarətdir. Belə ki, onlardan biri ikinci dəfə söndürüldükdə uçuşun davam etdirilməsini və ya təhlükəsiz enişin yerinə yetirilməsini təmin edir. Elektrik qurğusunun sağ və sol mühərrikləri işlənmiş şlamların bərpası şərtilə bir-birini əvəz edir.";
    let content2=lang==="en"?"The TVZ-117V helicopter gas turbine engine designed by S. P. Izotov was created taking into account domestic and foreign experience in design, production and operation. A special feature of the design of the turboshaft engine is the presence of a free turbine. The power generated by the free turbine is transferred to the main gearbox and makes up the effective power of the engine.":lang==="ru"?"Вертолетный газотурбинный двигатель ТВЗ-117В конструкции С.П. Изотова был создан с учетом отечественного и зарубежного опыта проектирования, производства и эксплуатации. Особенностью конструкции турбовального двигателя является наличие свободной турбины. Мощность, вырабатываемая свободной турбиной, передается главному редуктору и составляет эффективную мощность двигателя.":"S. P. İzotovanın konstruksiyasının helikopter qaz-turbin mühərriki-117V layihələndirmənin, istehsalın və istismarın yerli və xarici təcrübəsi nəzərə alınmaqla yaradılmışdır. Turboval Mühərrikin konstruksiyasının xüsusiyyəti azad turbinin olmasıdır. Sərbəst turbinlə istehsal olunan güc əsas reduktora ötürülür və mühərrikin effektiv gücünü təşkil edir.";
    let content3=lang==="en"?"This feature has a number of design and operational advantages:":lang==="ru"?"Эта особенность имеет ряд конструктивных и эксплуатационных преимуществ:":"Bu xüsusiyyət bir sıra konstruktiv və istismar faydaları:";
    let li1=lang==="en"?"allows you to get the desired speed of rotation of the rotor of a free turbine;":lang==="ru"?"позволяет получать желаемую частоту вращения ротора свободной турбины;":"pulsuz turbin rotorunun istənilən fırlanma tezliyini əldə etməyə imkan verir;";
    let li2=lang==="en"?"makes it easier to spin the turbocharger rotor when starting the engine;":lang==="ru"?"облегчает раскрутку ротора турбокомпрессора при запуске двигателя;":"mühərrikin işə salınmasında turbokompressor rotorunun açılmasını asanlaşdırır;";
    let li3=lang==="en"?"allows you to get optimal fuel consumption under different operating conditions of the engine;":lang==="ru"?"позволяет получать оптимальные расходы топлива при различных условиях эксплуатации двигателя;":"Mühərrikin istismarının müxtəlif şərtlərində optimal yanacaq xərclərini əldə etməyə imkan verir;";
    let li4=lang==="en"?"eliminates the need to install a friction clutch in the power plant of the helicopter.":lang==="ru"?"исключает необходимость установки фрикционной муфты в силовой установке вертолета.":"vertolyotun güc qurğusunda friksion muftanın quraşdırılmasının zəruriliyini istisna edir.";
    let other1=lang==="en"?"1. Engine weight (dry) 285 kg.":lang==="ru"?"1. Масса двигателя (сухого) 285 кг.":"1. Mühərrikin Çəkisi (quru) 285 kq.";
    let other2=lang==="en"?"2. Overall dimensions of the engine:":lang==="ru"?"2. Габаритные размеры двигателя:":"2. Mühərrikin qabarit ölçüləri:";
    
    let forOther2=lang==="en"?"* length with units and exhaust pipe 2055 mm.; * width 650 mm.; * height 728 mm.":lang==="ru"?"* длина с агрегатами и выхлопным патрубком 2055 мм.;* ширина 650 мм.;* высота 728 мм.":"* aqreqatlar və egzoz borusu olan uzunluq 2055 mm.; * eni 650 mm.; * hündürlüyü 728 mm.";;

    let other3=lang==="en"?"3. Output shaft power at standard atmosphere with ROM enabled(Н=0, V=0)":lang==="ru"?"3. Мощность на выводном валу при стандартной атмосфере с включенным ПЗУ ( при Н=0, V=0):":"3. ROM daxil olan standart atmosferdə çıxış valında güc (Н=0, V=0)";
    
    let forOther3=lang==="en"?"* take-off mode 2100 hp; * rated mode 1700 hp; * I cruising mode 1500 hp; * II cruising mode 1200 hp; * low gas no more than 200 hp.":lang==="ru"?"* взлётный режим 2100 л.с.;* номинальный режим 1700 л.с.;* I крейсерский режим 1500 л.с.;* II крейсерский режим 1200 л.с.;* малый газ не более 200 л.с.":"* Uçuş rejimi 2100 hp; * nominal rejimi 1700 hp; * ı seyir rejimi 1500 hp; * II seyir rejimi 1200 hp;* kiçik qaz 200 HP-dən çox deyil.";
    
    let other4=lang==="en"?"4. The maximum air flow through the compressor is 9.7 kg/s.":lang==="ru"?"4. Максимальный расход воздуха через компрессор 9,7 кг/с.":"4. Kompressor vasitəsilə maksimum hava istehlakı 9,7 kg/s.";
    let other5=lang==="en"?"5. The degree of pressure increase in the compressor is 9.9.":lang==="ru"?"5. Степень повышения давления в компрессоре 9,9.":"5. Kompressorda təzyiqin artması dərəcəsi 9,9.";

    let home=lang==="en"?"Home":lang==="ru"?"Главная":"Ana səhifə";

        return (
            <div>
                <Breadcrumb title={title}>
                    <BreadcrumbItem name={home} href="/" />
                    <BreadcrumbItem name={info1} href="/info" />
                    <BreadcrumbItem name={info2} href={adres} />
                    <BreadcrumbItem name={title} current />
                </Breadcrumb>

<div className="container">
<div className="row">
    <div className="col-12 col-md-6">
    <p> {content1}
<br/>
{content2}
</p>
    </div>
    <div className="col-12 col-md-6">
    <img src="http://авиару.рф/wp-content/uploads/2016/01/11.Dvigatel-TV3-117-v-razreze..jpg" alt="photo-1" width="100%" />
    </div>
</div>
<br/>
<div className="row">
    <div className="col-12">
<div>
{content3}
<br/>
<ul>
<li>{li1}</li>
<li>{li2}</li>
<li>{li3}</li>
<li>{li4}</li>
</ul>
<br/>
</div>
</div>

<div className="col-12" >
{other1}
<br/>
{other2}
<br/>
{forOther2}
<br/>
{other3}
<br/>
{forOther3}
<br/>
{other4}
<br/>
{other5}
<p></p>
</div>

</div>


</div>
<div className="forVideo" style={{textAlign:"center",width:"100%",height:"75vh",marginBottom:"10px"}}>
<iframe width="70%" height="100%" src="https://www.youtube.com/embed/2h6F61HsOMI" title="YouTube video player" frameBorder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen></iframe>
</div>
</div>
        )
    }
export default Common;
